name: Build and Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: false  # Prevents React from treating warnings as errors

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stratosafe_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: TypeScript Check
        run: |
          yarn workspace stratosafe-backend tsc --noEmit
          yarn workspace stratosafe-frontend tsc --noEmit

      - name: Build applications
        run: yarn build

      - name: Run database migrations
        run: |
          cd backend
          # Wait for database to be ready
          echo "Waiting for PostgreSQL to be ready..."
          timeout 30 bash -c "until pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done"
          # Set environment variables
          export DB_HOST=postgres
          export DB_PORT=5432
          export DB_USERNAME=postgres
          export DB_PASSWORD=postgres
          export DB_DATABASE=stratosafe_test
          # Run migrations
          yarn run typeorm migration:run -d src/data-source.ts
        env:
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_DATABASE: stratosafe_test
