name: Docker Hub Build and Publish

on:
  push:
    branches: [main, master]
  workflow_dispatch:  # Allow manual triggering
  workflow_run:
    workflows: ["Build and Test", "Lint"]
    types:
      - completed
    branches: [main, master]

jobs:
  fetch-secrets-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with HCP and get secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://api.cloud.hashicorp.com/secrets/2023-06-13
          method: jwt
          jwtGithubAudience: https://api.cloud.hashicorp.com
          jwtTtl: 300
          exportToken: true
          secrets: |
            apps/data/stratosafe/dockerhub_username DOCKERHUB_USERNAME | DOCKERHUB_USERNAME ;
            apps/data/stratosafe/dockerhub_token DOCKERHUB_TOKEN | DOCKERHUB_TOKEN ;
            apps/data/stratosafe/db_username DB_USERNAME | DB_USERNAME ;
            apps/data/stratosafe/db_password DB_PASSWORD | DB_PASSWORD ;
            apps/data/stratosafe/jwt_secret JWT_SECRET | JWT_SECRET

      - name: Log which secrets were successfully retrieved
        run: |
          echo "Retrieved the following secrets (showing variable names only, not values):"
          [[ -n "$DOCKERHUB_USERNAME" ]] && echo "- DOCKERHUB_USERNAME" || echo "! DOCKERHUB_USERNAME missing"
          [[ -n "$DOCKERHUB_TOKEN" ]] && echo "- DOCKERHUB_TOKEN" || echo "! DOCKERHUB_TOKEN missing"
          [[ -n "$DB_USERNAME" ]] && echo "- DB_USERNAME" || echo "! DB_USERNAME missing"
          [[ -n "$DB_PASSWORD" ]] && echo "- DB_PASSWORD" || echo "! DB_PASSWORD missing"
          [[ -n "$JWT_SECRET" ]] && echo "- JWT_SECRET" || echo "! JWT_SECRET missing"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/stratosafe-backend:latest,${{ env.DOCKERHUB_USERNAME }}/stratosafe-backend:${{ github.sha }}
          build-args: |
            DB_USERNAME=${{ env.DB_USERNAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            JWT_SECRET=${{ env.JWT_SECRET }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/stratosafe-frontend:latest,${{ env.DOCKERHUB_USERNAME }}/stratosafe-frontend:${{ github.sha }}
