name: Docker Hub Build and Publish

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-secrets-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Obtain HCP OAuth Token
        id: hcp-auth
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: |
          # Request OAuth token from HCP
          response=$(curl -s -X POST https://auth.idp.hashicorp.com/oauth2/token \
            -H "Content-Type: application/json" \
            -d '{
              "audience": "https://api.hashicorp.cloud",
              "grant_type": "client_credentials",
              "client_id": "'"$HCP_CLIENT_ID"'",
              "client_secret": "'"$HCP_CLIENT_SECRET"'"
            }')
          
          # Extract token from response
          token=$(echo "$response" | jq -r '.access_token')
          
          if [ -z "$token" ] || [ "$token" = "null" ]; then
            echo "Failed to obtain OAuth token. Response: $response"
            exit 1
          fi
          
          # Set token as output and environment variable
          echo "token=$token" >> $GITHUB_OUTPUT
          echo "HCP_API_TOKEN=$token" >> $GITHUB_ENV
          echo "Successfully obtained HCP OAuth token"

      - name: Authenticate with HCP and get secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://api.cloud.hashicorp.com/secrets/2023-11-28/organizations/$HCP_ORGANIZATION_ID/projects/$HCP_PROJECT_ID/apps/$APP_NAME/secrets
          method: token
          token: ${{ env.HCP_API_TOKEN }}
          secrets: |
            apps/data/stratosafe/dockerhub_username DOCKERHUB_USERNAME | DOCKERHUB_USERNAME ;
            apps/data/stratosafe/dockerhub_token DOCKERHUB_TOKEN | DOCKERHUB_TOKEN ;
            apps/data/stratosafe/db_username DB_USERNAME | DB_USERNAME ;
            apps/data/stratosafe/db_password DB_PASSWORD | DB_PASSWORD ;
            apps/data/stratosafe/jwt_secret JWT_SECRET | JWT_SECRET

      - name: Log which secrets were successfully retrieved
        run: |
          echo "Retrieved the following secrets (showing variable names only, not values):"
          [[ -n "$DOCKERHUB_USERNAME" ]] && echo "- DOCKERHUB_USERNAME" || echo "! DOCKERHUB_USERNAME missing"
          [[ -n "$DOCKERHUB_TOKEN" ]] && echo "- DOCKERHUB_TOKEN" || echo "! DOCKERHUB_TOKEN missing"
          [[ -n "$DB_USERNAME" ]] && echo "- DB_USERNAME" || echo "! DB_USERNAME missing"
          [[ -n "$DB_PASSWORD" ]] && echo "- DB_PASSWORD" || echo "! DB_PASSWORD missing"
          [[ -n "$JWT_SECRET" ]] && echo "- JWT_SECRET" || echo "! JWT_SECRET missing"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/stratosafe-backend:latest,${{ env.DOCKERHUB_USERNAME }}/stratosafe-backend:${{ github.sha }}
          build-args: |
            DB_USERNAME=${{ env.DB_USERNAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            JWT_SECRET=${{ env.JWT_SECRET }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/stratosafe-frontend:latest,${{ env.DOCKERHUB_USERNAME }}/stratosafe-frontend:${{ github.sha }}
