name: Docker Hub Build and Publish

on:
  push:
    branches: [main, master]
  workflow_dispatch:  # Allow manual triggering
  workflow_run:
    workflows: ["Build and Test", "Lint"]
    types:
      - completed
    branches: [main, master]

permissions:
  contents: read
  id-token: write  # Critical for OIDC token generation

jobs:
  fetch-secrets-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with HCP and get secrets
        uses: hashicorp/vault-action@v2
        id: secrets
        with:
          url: https://api.cloud.hashicorp.com/secrets/2023-06-13
          method: jwt
          path: jwt  # HCP Vault JWT auth path
          role: github-actions  # Your configured HCP Vault role
          jwtGithubAudience: https://api.cloud.hashicorp.com
          jwtTtl: 300
          exportToken: true
          secrets: |
            apps/data/stratosafe/dockerhub_username DOCKERHUB_USERNAME | DOCKERHUB_USERNAME ;
            apps/data/stratosafe/dockerhub_token DOCKERHUB_TOKEN | DOCKERHUB_TOKEN ;
            apps/data/stratosafe/db_username DB_USERNAME | DB_USERNAME ;
            apps/data/stratosafe/db_password DB_PASSWORD | DB_PASSWORD ;
            apps/data/stratosafe/jwt_secret JWT_SECRET | JWT_SECRET

      - name: Validate secret retrieval
        run: |
          if [[ -z "$DOCKERHUB_USERNAME" ]]; then
            echo "Error: Failed to retrieve DockerHub username"
            exit 1
          fi
          echo "Secrets retrieved successfully"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/stratosafe-backend:latest,${{ env.DOCKERHUB_USERNAME }}/stratosafe-backend:${{ github.sha }}
          build-args: |
            DB_USERNAME=${{ env.DB_USERNAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            JWT_SECRET=${{ env.JWT_SECRET }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/stratosafe-frontend:latest,${{ env.DOCKERHUB_USERNAME }}/stratosafe-frontend:${{ github.sha }}
